GET http://localhost:3000/employees

###
GET http://localhost:3000/employees/1

###
POST http://localhost:3000/employees

Content-Type: application/json

{
    "name": "Banu",
    "license_no": "LN101",
    "age": 24,
    "salary": 24000
}
